'use strict';
const db=require('./db');
const STORE='dating', MIN_AGE=18;
function get(){const d=db.get(STORE,'data',{});return {profiles:d.profiles||{},pending:d.pending||{},proposals:d.proposals||{},blocks:d.blocks||{}};}
function save(d){db.set(STORE,'data',d);} function k(c){return c.sender;} function num(j){return String(j||'').split('@')[0].split(':')[0].replace(/[^0-9]/g,'');} function clean(v,n){return String(v||'').trim().replace(/[\r\n]+/g,' ').slice(0,n||240);} function foot(c){return c.settings?.FOOTER||'';} function reply(c,t){return c.reply(t+foot(c));} function adult(p){return Number(p&&p.age)>=MIN_AGE;} function name(p){return p.name||p.number||'Unknown';}
function start(c){const d=get();d.pending[k(c)]={step:'age',profile:{jid:c.sender,number:num(c.sender),name:clean(c.pushName,80)}};save(d);return reply(c,'💞 *DATE REGISTRATION*\\n\\nLet’s create your private dating profile.\\n\\n*1/6 Age:* How old are you? (18+ is required for Sex Zone)');}
async function finish(c,x){const d=get();const p={...x.profile,public:true,available:true,registeredAt:Date.now()};d.profiles[k(c)]=p;delete d.pending[k(c)];save(d);return reply(c,'✅ *Profile saved!*\\n\\n*Name:* '+p.name+'\\n*Age:* '+p.age+'\\n*Gender:* '+p.gender+'\\n*Location:* '+(p.location||'Not shared')+'\\n*Status:* '+p.status+'\\n*Bio:* '+(p.bio||'No bio yet')+'\\n\\nUse *'+c.prefix+'date* to find a match or *'+c.prefix+'mydate* to view your profile.');}
async function handlePendingText(sock,msg,c){if(!c.isPrivate||c.isCmd||!c.body?.trim())return false;const d=get(),x=d.pending[k(c)];if(!x)return false;const a=clean(c.body,500);if(x.step==='match-select')return select(sock,msg,c,x);if(x.step==='age'){const v=Number(a);if(!Number.isInteger(v)||v<13||v>120){await reply(c,'❌ Please enter a valid age between 13 and 120.');return true;}x.profile.age=v;x.step='gender';save(d);await reply(c,'*2/6 Gender:* Reply with *male* or *female*.');return true;}if(x.step==='gender'){const v=a.toLowerCase();if(v!=='male'&&v!=='female'){await reply(c,'❌ Please reply with *male* or *female*.');return true;}x.profile.gender=v;x.step='location';save(d);await reply(c,'*3/6 Location:* Where are you based? Reply *skip* to keep it private.');return true;}if(x.step==='location'){x.profile.location=/^skip$/i.test(a)?'':clean(a,80);x.step='status';save(d);await reply(c,'*4/6 Relationship status:* e.g. *single*, *complicated*, or *prefer not to say*.');return true;}if(x.step==='status'){x.profile.status=clean(a,40);x.step='bio';save(d);await reply(c,'*5/6 Bio:* Tell people a little about you, or reply *skip*.');return true;}if(x.step==='bio'){x.profile.bio=/^skip$/i.test(a)?'':clean(a,240);x.step='public';save(d);await reply(c,'*6/6 Public matching:* Reply *yes* to appear in matches, or *no* to stay hidden.');return true;}if(x.step==='public'){if(!/^(yes|no)$/i.test(a)){await reply(c,'❌ Reply *yes* or *no*.');return true;}x.profile.public=/^yes$/i.test(a);await finish(c,x);return true;}return false;}
function fmt(p,i){return '*'+i+'. '+name(p)+'*\\n┋ 🎂 '+p.age+'  ┋ ⚧ '+p.gender+'\\n┋ 📍 '+(p.location||'Not shared')+'\\n┋ 💬 '+(p.bio||'No bio yet')+'\\n┋ '+(p.available?'🟢 Available':'⏸️ Paused');}
async function matches(sock,msg,c){const d=get(),me=d.profiles[k(c)];if(!me)return start(c);if(!me.public||!me.available)return reply(c,'⏸️ Your profile is hidden or paused. Use *'+c.prefix+'setdate public yes* and *'+c.prefix+'setdate available yes* to join matchmaking.');const list=Object.entries(d.profiles).filter(([j,p])=>j!==k(c)&&p.public&&p.available&&p.gender!==me.gender&&!((d.blocks[k(c)]||[]).includes(j)||(d.blocks[j]||[]).includes(k(c))));if(!list.length)return reply(c,'💞 No available matches yet. Your profile is active—try again later.');d.pending[k(c)]={step:'match-select',matches:list.slice(0,10).map(x=>x[0])};save(d);return reply(c,'💞 *AVAILABLE MATCHES*\\n\\n'+list.slice(0,10).map((x,i)=>fmt(x[1],i+1)).join('\\n\\n')+'\\n\\nReply with a number (1-'+Math.min(list.length,10)+') to send a date proposal, or *cancel*.');}
async function select(sock,msg,c,x){const a=c.body.trim().toLowerCase(),d=get();if(a==='cancel'){delete d.pending[k(c)];save(d);await reply(c,'👌 Match selection cancelled.');return true;}const i=Number(a)-1;if(!Number.isInteger(i)||!x.matches?.[i]){await reply(c,'❌ Reply with one of the numbers shown, or *cancel*.');return true;}const target=x.matches[i],p=d.profiles[target],me=d.profiles[k(c)];if(!p||!p.public||!p.available){delete d.pending[k(c)];save(d);await reply(c,'❌ That profile is no longer available. Run *'+c.prefix+'date* again.');return true;}d.proposals[target]={from:k(c),to:target,fromProfile:{name:me.name,age:me.age,gender:me.gender,location:me.location,bio:me.bio},status:'pending',createdAt:Date.now()};delete d.pending[k(c)];save(d);await sock.sendMessage(target,{text:'💌 *DATE PROPOSAL*\\n\\n'+name(me)+' ('+me.age+') would like to connect with you.\\n\\n*Bio:* '+(me.bio||'No bio yet')+'\\n*Location:* '+(me.location||'Not shared')+'\\n\\nReply *'+c.prefix+'accept* to connect or *'+c.prefix+'reject* to pass.'});await reply(c,'✅ Proposal sent to *'+name(p)+'*. I’ll notify you when they respond.');return true;}
async function accept(sock,msg,c){const d=get(),pr=d.proposals[k(c)],me=d.profiles[k(c)],from=pr&&d.profiles[pr.from];if(!pr||pr.status!=='pending')return reply(c,'📭 You have no pending date proposals.');if(!from||!me)return reply(c,'❌ This proposal is no longer available.');pr.status='accepted';save(d);const card=p=>({displayName:name(p),contacts:[{vcard:'BEGIN:VCARD\\nVERSION:3.0\\nFN:'+name(p)+'\\nTEL;type=CELL;type=VOICE;waid='+p.number+':+'+p.number+'\\nEND:VCARD'}]});await sock.sendMessage(c.from,card(from));await sock.sendMessage(pr.from,{text:'🎉 *MATCH ACCEPTED!*\\n\\n'+name(me)+' accepted your date proposal. You can now connect directly.'});await sock.sendMessage(pr.from,card(me));return reply(c,'🎉 *It’s a match!* '+name(from)+'’s contact has been sent to you.');}
async function reject(sock,msg,c){const d=get(),pr=d.proposals[k(c)];if(!pr||pr.status!=='pending')return reply(c,'📭 You have no pending date proposals.');pr.status='rejected';save(d);await sock.sendMessage(pr.from,{text:'💬 Your date proposal was politely declined. Keep meeting people!'});return reply(c,'👌 Proposal declined politely.');}
async function view(c){const p=get().profiles[k(c)];if(!p)return start(c);return reply(c,'👤 *MY DATE PROFILE*\\n\\n'+fmt(p,1)+'\\n┋ 🌐 Public: '+(p.public?'Yes':'No'));}
async function setDate(c,a){const d=get(),p=d.profiles[k(c)];if(!p)return start(c);const f=(a[0]||'').toLowerCase(),v=a.slice(1).join(' ').trim();if(f==='public'||f==='available'){if(!/^(yes|no|true|false)$/i.test(v))return reply(c,'❌ Usage: *'+c.prefix+'setdate '+f+' yes|no*');p[f]=/^(yes|true)$/i.test(v);}else if({location:1,status:1,bio:1}[f]){if(!v)return reply(c,'❌ Usage: *'+c.prefix+'setdate '+f+' your value*');p[f]=clean(v,{location:80,status:40,bio:240}[f]);}else return reply(c,'✏️ Usage: *'+c.prefix+'setdate location|status|bio|public|available value*');save(d);return reply(c,'✅ Updated *'+f+'*.');}
async function toggle(c,v){const d=get(),p=d.profiles[k(c)];if(!p)return start(c);p.available=v;save(d);return reply(c,v?'✅ You are available for matchmaking again.':'⏸️ Matchmaking paused.');}async function sex(c){const p=get().profiles[k(c)];if(!p)return start(c);if(!adult(p))return reply(c,'🔒 *18+ feature locked.* Your saved age does not meet the minimum age for Sex Zone.');return reply(c,'🔞 *SEX ZONE*\\n\\nAge verified. Keep all interactions consensual, respectful, and within the law.');}async function block(c,a){const t=(c.getMentions?.()||[])[0]||a[0];if(!t)return reply(c,'❌ Mention a user or provide a WhatsApp number.');const d=get();d.blocks[k(c)]=Array.from(new Set([...(d.blocks[k(c)]||[]),t]));save(d);return reply(c,'🚫 User blocked from your matches.');}
module.exports={handlePendingText,matches,select,accept,reject,view,setDate,toggle,sex,block};
