'use strict';

const {
    generateWAMessageFromContent,
    prepareWAMessageMedia,
    proto,
} = require('@itsliaaa/baileys');

function nativeFlowBizNode() {
    return [{
        tag: 'biz',
        attrs: {},
        content: [{
            tag: 'interactive',
            attrs: { type: 'native_flow', v: '1' },
            content: [{ tag: 'native_flow', attrs: { v: '9', name: 'mixed' } }],
        }],
    }];
}

async function sendImageCarousel({ sock, msg, from, images, title = 'MADARA IMAGE STUDIO', caption = '' }) {
    const buffers = (Array.isArray(images) ? images : [images]).filter(Boolean);
    if (!buffers.length) throw new Error('No image was generated.');

    if (!proto?.Message?.InteractiveMessage?.CarouselMessage) {
        return sock.sendMessage(from, {
            image: buffers[0],
            caption,
        }, { quoted: msg });
    }

    const cards = [];
    for (let i = 0; i < buffers.length; i += 1) {
        const { imageMessage } = await prepareWAMessageMedia(
            { image: buffers[i] },
            { upload: sock.waUploadToServer },
        );
        cards.push(proto.Message.InteractiveMessage.fromObject({
            header: { title: `${title} ${i + 1}/${buffers.length}`, hasMediaAttachment: true, imageMessage },
            body: { text: caption || 'Generated by Madara X-MD.' },
            footer: { text: 'MADARA X-MD' },
            nativeFlowMessage: {
                buttons: [{
                    name: 'quick_reply',
                    buttonParamsJson: JSON.stringify({
                        display_text: 'Generate another',
                        id: 'madara_generate_again',
                    }),
                }],
            },
        }));
    }

    const interactiveMessage = proto.Message.InteractiveMessage.fromObject({
        body: { text: caption || 'Your generated image is ready.' },
        footer: { text: 'MADARA X-MD · IMAGE STUDIO' },
        header: { title, hasMediaAttachment: false },
        carouselMessage: proto.Message.InteractiveMessage.CarouselMessage.fromObject({ cards }),
    });

    const wrapped = generateWAMessageFromContent(from, {
        viewOnceMessage: {
            message: {
                messageContextInfo: { deviceListMetadataVersion: 2, deviceListMetadata: {} },
                interactiveMessage,
            },
        },
    }, { userJid: sock.user?.id, quoted: msg });

    await sock.relayMessage(from, wrapped.message, {
        messageId: wrapped.key.id,
        additionalNodes: nativeFlowBizNode(),
    });
}

module.exports = { sendImageCarousel };